server:
    port: 9090
    forward-headers-strategy: native
    servlet:
        session: 
            cookie:
                secure: true
spring:
    task:
        executor:
            pool:
                core-size: 10
                max-size: 50
            queue-capacity: 100
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 5MB
    cloud:
        vault:
            application-name: credentials
            authentication: TOKEN
            token: hvs.iuknxC0wUc3wjcO70ZCH9kS0
            scheme: http
            port: 8200
            host: localhost
    config:
        import: vault://kv/credentials
    application:
        name: app_pn
    datasource:
        url: ${db.url}
        username: ${db.username}
        password: ${db.password}
        hikari:
            max-lifetime: 60000 
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
        hibernate.ddl-auto: update
        generate-ddl: false
        show-sql: false
    # security:
    #     oauth2:
    #         client:
    #             registration:
    #                 google:
    #                     client-id: ${client_id_web}
    #                     client-secret: ${client_secret_web}
    #                     scope: 
    #                         - profile
    #                         - email
    #                         - openid
    #                     redirect-uri: "https://apppn.duckdns.org/oauth2/callback"
    #                     authorization-grant-type: authorization_code
    #                     client-name: Google
    #             provider:
    #                 google:
    #                     authorization-uri: https://accounts.google.com/o/oauth2/auth
    #                     token-uri: https://oauth2.googleapis.com/token
    #                     user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
google:
    clientId:  ${client_id_web}
    clientIdMovil: ${client_id_movil}
    client-secret: ${client_secret_web}

    
jwt:
    secret: ${jwt.secret}

url: /data/uploads/
firm:
    secret: ${firm.secret}
secretAES: ${secretAES}
ivAES: ${ivAES}
# logging:
#   level:
#     org.springframework.vault: DEBUG
management:
    endpoints:
        web:
            exposure:
                include: '*'

url-back: http://localhost:9090